### ISSUE TITLE
Ampersands being eaten

### ISSUE THREAD

**Issue by siwelwerd** [StevenClontz/Mastr#5]
I believe Mastr is eating ampersands. They appear in the seeds.json file, but then do not appear in the xml or latex output.

**Comment by siwelwerd** [comment]
Maybe this is why?

https://github.com/sparklemotion/nokogiri/issues/1705

**Comment by siwelwerd** [comment]
Added lin-alg/V9 to this project, which exhibits the error.

**Comment by StevenClontz** [comment]
Yeah `&` is a reserved character in XML. I think the correct thing is to have seeds.json contain valid XML snippets, so use `&amp;`.

I forget my hacky implementation of `XML->LaTeX` so it's quite likely that will cause errors in the LaTeX output.

**Comment by StevenClontz** [comment]
Oh I see. The Sagemath code is producing `&`, so I need to figure out how to clean that up. Or maybe I'm mistaken: seeds.json should contain valid LaTeX snippets, which I'll need to handle.

**Comment by siwelwerd** [comment]
Yeah. Compare the following two lines:

`v1="\\begin{bmatrix}"+ latex(vec1[0])+" &amp; "+ latex(vec1[1]) +" \\\\ "+ latex(vec1[2]) +" &amp; "+latex(vec1[3]) +"\\end{bmatrix}"
v2=latex(matrix([[vec2[0],vec2[1]],[vec2[2],vec2[3]]]))`

v1 prints okay now, v2 is obviously more elegant but the latex() call throws a plain & that gets eaten.

**Comment by StevenClontz** [comment]
Drew reopen if this doesn't address the issue.
