### ISSUE TITLE
Extra newlines in exercises

### ISSUE THREAD

**Issue by siwelwerd** [StevenClontz/Mastr#6]
There seem to be an extra newline at the beginning of each exercise statement that we don't necessarily want.

**Comment by siwelwerd** [comment]
I think this is the culprit:
https://github.com/StevenClontz/Mastr/blob/7460c36f36b705933feca18833f122e1671b2b45/mastr.rb#L69

**Comment by siwelwerd** [comment]
I am wondering if replacing this with 
`tag.replace tag.inner_html+"\n\n" `
would have any unintended consequences.

**Comment by StevenClontz** [comment]
I implemented your suggestion (but didn't check for consequences!!).

**Comment by siwelwerd** [comment]
So far so good; will reopen if I notice any unintended consequences.

**Comment by siwelwerd** [comment]
I seem to have found an unintended consequence, but I don't understand why. Looking at TBIL G1 problems, something like

`<statement>`
`<p>(a) Part a</p>`
`<p>(b) Part b</p>`
`...`
`</statement>`


Based on 
https://github.com/StevenClontz/Mastr/blob/dcd7dcb5109a1d94d8957f8dac99de5b6d33329c/mastr.rb#L78

I think there should be two newlines between parts a and b. But the generated LaTeX seems to have no newlines.

**Comment by StevenClontz** [comment]
I think d6b09da fixes this - that whitespace was being eaten later in the script, so I reordered how things are done. Check and close if you're happy.
