### ISSUE TITLE
Multiline math

### ISSUE THREAD

**Issue by siwelwerd** [StevenClontz/Mastr#9]
For future proofing, I am assuming the xml should contain PreTeXt tags like <md> and <mrow> to handle multi line math. In fe7ac43 I added in code to handle this  in LaTeX (using \begin{align*}), but I am not sure how to properly do this in the HTML output.

**Comment by StevenClontz** [comment]
The same conversion may *just work^TM* if my recollection of how MathJaX is implemented holds. Did you implement this in an exercise yet? If so, I'll get the HTML working.

That said, I'm loathe to add many more features to this conversation script as it's part of the Ruby component that needs to be dropped. (In particular, XML transformations should be handled by, well, [XML transformations](https://www.w3.org/standards/xml/transformation).)

**Comment by siwelwerd** [comment]
Yeah, I think this came up in V10 problems.  I think my point is that the "correct" way to write multiline math in pretext is using md and mrow tags.  So there is a small tension between "Don't put effort into Mastr ruby code" and "Write problems in the correct PreTeXt way", and I think this one feature is used so often in LA (for systems of equations) that we want to favor writing problems the correct PreTeXt way.

**Comment by StevenClontz** [comment]
Yep - I plan to implement this because you're right, but hopefully we can get by without adding too much more of the PreTeXt syntax until I find a better way to use PreTeXt directly, perhaps in this thread: https://groups.google.com/forum/#!msg/pretext-dev/7S5ECJLzj9Y/wm0K-hRtBAAJ

**Comment by StevenClontz** [comment]
Literally a copy-paste of your work, but 0ff96d5364180fc293d59bf6c497372cad25372c closes this.
